final_space = true
enable_cursor_positioning = true
version = 2

[var]
git="git status"

[[blocks]]
type="prompt"
newline = true
alignment="left"
overflow="break"
leading_diamond = " >>>>"
trailing_diamond=">>"

  [[blocks.segments]]
  type="path"
  style='plain'
  foreground="#51afef"

    [blocks.segments.properties]
    style="folder"
    folder_icon=""
    max_depth = 3
    # hide_root_location=true
template="{{ .Location}}"
    # template= "{{ if .RepoName }}{{ .Location }}{{ else }}{{ .Path }}{{end}}"
    [blocks.segments.properties.mapped_locations]
    '~/.local/share/applications' ='󰀻 Applications'
    '~/Downloads' ='  Downloads'
    '~/Downloads/*' ='  Downloads'

  [[blocks.segments]]
  type="git"
  foreground="#a9a1e1"
# foreground_templates= [
#   "{{ if gt .Staging.Modified 0}}yellow{{end}}",
#   "{{ if gt .Staging.Added 0}}red{{end}}"
# ]
  template="""{{ if .Detached }} \uE0A0 HEAD{{ else }}{{ .HEAD}} {{ end }}\
  {{ .Upstream }}\
  {{ if and (gt .Ahead 0) (eq .Behind 0) }} ⇡{{.Ahead}}{{ end }}\
  {{ if and (eq .Ahead 0) (gt .Behind 0) }} ⇣{{.Behind}}{{ end }}\
  {{ if and (gt .Ahead 0) (gt .Behind 0) }}  ⇡{{.Ahead}}⇣{{.Behind}}{{ end }}\
  {{ if .Staging.Changed }}{{if gt .Staging.Added 0 }} +{{.Staging.Added}}{{else if gt .Staging.Modified 0}} +{{.Staging.Modified}}{{else}} {{.Staging.String}}{{ end }}{{ end }}\
  {{ if .Working.Changed }} {{.Working.String}}{{ end }}\
  {{ if gt .StashCount 0 }} ${{ .StashCount}}{{ end }}\
  {{ if .Detached}} ({{ .Commit.Sha | printf \"%.7s\"}} {{.Ref}}){{end}}\
  """
  [blocks.segments.properties.staging.modified]
  foreground="green"

  # template="[{{ join \", \" .Commit.Refs.Tags }}]"
    [blocks.segments.properties]
    source="cli"
    branch_icon="\uE0A0 "
    commit_icon="\uF417 "
    tag_icon="\uF412 "
    rebase_icon="\uE728 "
    cherry_pick_icon="\uE29B "
    revert_icon="\uF0E2 "
    merge_icon="\uE727 "
    no_commits_icon="\uF594 "
    fetch_status=true
    full_branch_path = false
    fetch_upstream_icon = false
      [blocks.segments.properties.mapped_branches]
      "feature/*" ="feat:"
      "hotfix/*" = "hf:"
      "bugfix/*" = "bug:"
      "test/*" = "test:"
      "merge/*" = "merge:"
      "build/*" = "build:"
      "release/*" = "rel:"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  type = "text"
  foreground_templates = ["{{if .Code}}red{{ else }}green{{end}}"]
  style = "plain"
  template = "{{ if ne .Code 0 }}✗{{ else if .Env.TMUX}}w{{ else }}➜{{end}}"

[transient_prompt]
template = "▶ "
foreground = "green"

