TeamViewer User Settings
# It is not recommended to edit this file manually


[strng] BuddyLoginName = "arbeerafiq@gmail.com"
[int32] ConfigurationRMAssetReportingEnabled = 1
[int32] LastCorrectorRun = 2
[int32] MainWindowSize = 888 526 311 503
[int32] OnboardingTaskState = 1 1 1
[int32] PilotTabWasEnabled = 1
[bin  ] SUID = cac8210f338d45219eeedad17645078f
[int32] SuitedForOnboarding = 1
