[window]
opacity = 0.85
padding.x = 3
padding.y = 0
decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Medium"
bold.style = "Bold"
italic.style ="Italic"
bold_italic.style = "Bold Italic"
size = 11

[colors.bright]
black = '#767676'
blue = '#a9a1e1'
cyan = '#51afef'
# green = '#99bb66'
green = "#090a0a"
magenta = '#c678dd'
red = '#ff6655'
# white = '#bfbfbf'
white = "#000000"
yellow = '#ecbe7b'

[colors.cursor]
cursor = '#51afef'
text = '#1b1b1b'

[colors.normal]
black = '#000000'
blue = '#a9a1e1'
cyan = '#51afef'
green = '#98be65'
magenta = '#c678dd'
red = '#ff6c6b'
white = '#bbc2cf'
yellow = '#ecbe7b'

[colors.primary]
background = '#090a0a'
foreground = '#bbc2cf'

[colors.selection]
# text = '#42444b'
text="#090a0a"
background = '#bbc2cf'

[env]
TERM = "xterm-256color"
