include current-theme.conf
# END_KITTY_THEME

font_family      family='JetBrainsMono Nerd Font' features=-calt
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
disable_ligatures all always

cursor #cccccc
cursor_text_color #111111
cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0

enable_audio_bell no
window_padding_width 4.0
active_border_color #2257a0
hide_window_decorations yes
confirm_os_window_close 0
tab_bar_edge top
tab_bar_margin_width 2.0
tab_bar_style powerline
tab_bar_align left
tab_powerline_style round
tab_title_template "{session_name} {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"
active_tab_foreground   #191724
active_tab_background   #51afef
tab_bar_background none
background #000000
background_opacity 0.85
selection_background #c1c1c1
enabled_layouts splits
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -


# example 
# action_alias launch_tab launch --type=tab --cwd=current
# map f1 launch_tab nvim

map kitty_mod+t no_op
map kitty_mod+e pass_selection_to_program
map alt+shift+= launch --location=vsplit
map alt+shift+- launch --location=hsplit
map kitty_mod+l launch --type=tab --cwd=current lazygit

map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter 3
# reset all windows in the tab to default sizes
map ctrl+home resize_window reset

map alt+shift+k move_window up
map alt+shift+h move_window left
map alt+shift+l move_window right
map alt+shift+j move_window down

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map kitty_mod+c new_tab_with_cwd
map kitty_mod+m next_layout
map kitty_mod+o open_url_with_hints
map kitty_mod+f5 load_config_file
