[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
padding.x = 3
padding.y = 0
decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Medium"
bold.style = "Bold"
italic.style ="Italic"
bold_italic.style = "Bold Italic"
size = 12

[colors.bright]
black = '#8f8d8d'
white = "#dfdfdf"
cyan = '#51afef'
blue = '#a9a1e1'
green = '#98be65'
magenta = '#c678dd'
red = '#ff665b'
yellow = '#ecbe7b'

[colors.cursor]
cursor = '#51afef'
text = '#1b1b1b'

[colors.normal]
black = '#1c1f24'
white = '#dfdfdf'
cyan = '#51afef'
blue = '#2257a0'
green = '#98be75'
magenta = '#a9a1e1'
red = '#ff6c6b'
yellow = '#ecbe7b'

[colors.primary]
background = '#090a0a'
foreground = '#cfd7e6'
bright_foreground = "#cfd7e7"

[colors.selection]
text="#1c1f24"
background = '#cfd7e6'

