set -g @continuum-restore 'on'
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

#remap window index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#set vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -n M-1 selectw -t 1
bind-key -n M-2 selectw -t 2
bind-key -n M-3 selectw -t 3
bind-key -n M-4 selectw -t 4
bind-key -n M-5 selectw -t 5
bind-key -n M-6 selectw -t 6
bind-key -n M-7 selectw -t 7
bind-key -n M-8 selectw -t 8
bind-key -n M-9 selectw -t 9

#set inactive/active window styles
set -g pane-active-border-style "fg=colour244"
set -g pane-border-style "fg=magenta"

#Custom KeyBinds
# bind -n M-H previous-window
# bind -n M-L next-window
bind -n M-C new-window

#open panes in same dir
bind -n M-+ split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"

#Plugins tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

# set -g @catppuccin_window_left_separator ""
# set -g @catppuccin_window_right_separator " "
# set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_number_position "right"
#
# #set -g @catppuccin_window_default_fill "number"
# #set -g @catppuccin_window_default_text "#W"
#
# set -g @catppuccin_window_current_fill "number"
# set -g @catppuccin_window_current_text "#{b:pane_current_path}"
#
# set -g @catppuccin_status_modules_right "application session cpu date_time"
# set -g @catppuccin_date_time_text "%H:%M %d-%m"
# set -g @catppuccin_status_left_separator  " "
# set -g @catppuccin_status_right_separator ""
# set -g @catppuccin_status_right_separator_inverse "no"
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_status_enable "yes"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{b:pane_current_path}"

set -g @catppuccin_status_modules_right "application session cpu date_time"
set -g @catppuccin_date_time_text "%H:%M %d-%m"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"
#set -g @catppuccin_directory_text "#{pane_current_path}"
# in .tmux.conf
set -g @plugin 'tmux-plugins/tmux-continuum'



run '~/.tmux/plugins/tpm/tpm'
