set -g @continuum-restore 'off'
# set -ga terminal-overrides ",xterm*:Tc"
# set-option -g terminal-overrides ",xterm-256color:RGB"
set-option -g default-terminal 'screen-256color'
set -g mouse on

#remap window index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g mode-keys vi

#remap
unbind C-b
unbind s
# unbind i
unbind n
unbind p
unbind c
set-option -g prefix C-t # try lu
bind-key C-t send-prefix

# remap binds
bind o choose-session # TODO: use the default; wip on tmux-session-manager.sh
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9
bind t new-window
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#set inactive/active window styles
set -g pane-active-border-style "fg=colour244"
set -g pane-border-style "fg=magenta"
set -g escape-time 0
#open panes in same dir
bind -n M-+ split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"

# personal plugins/binds
bind r source-file ~/dotfiles/tmux/.config/tmux/tmux.conf
# scripts
bind m run-shell "tmux popup -E -w 60% -h 70% '~/.local/scripts/fzf-man.sh'"
bind n run-shell "tmux popup -E -w 60% -h 70% ~/.local/scripts/tmux-session.sh" #
bind l run-shell 'tmux neww sh -c "cd \$(tmux display-message -p \"#{pane_current_path}\") && lazygit"'
# bind o run-shell "$XDG_CONFIG_HOME/tmux/plugins/tmux-sessionx/scripts/sessionx.sh"


#Plugins tmux
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# theme
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_middle_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_fill "number"

set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
# set -g @catppuccin_status_connect_separator "yes"

# set -g @catppuccin_window_current_text "#{b:pane_current_path}"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_status_modules_right "session date_time"
set -g @catppuccin_date_time_text "%H:%M %d-%m"

run '$XDG_CONFIG_HOME/tmux/plugins/tpm'
#run '~/.tmux/plugins/tpm/tpm' -> if is in home
