set -g @continuum-restore 'on'
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ",*256*:Tc"
set -g mouse on
set -g status-position top
set -g mode-style "bg=#a0a1e1,fg=#090a00"
set -g status-style "fg=#51afef,bg=#191724"
set -g status-left-length "200"
set -g status-right-length "200"
set -g pane-active-border-style "fg=#2257a0"
set -g pane-border-status "off"
set -g pane-border-lines "single"
set -g pane-border-indicators "colour"
set -g popup-border-style "fg=#2257a0"
set -g pane-border-style "fg=#000000"
# set -g display-panes-active-colour ""
set -g window-status-bell-style "bg=red"
set -g window-status-activity-style "bg=red"
set -g window-status-current-format "*#W "
set -g window-status-current-style "fg=#a9a1e1,bold"
set -g window-status-format " #W "
set -g window-status-style "fg=#51afef"
set -g window-status-last-style "fg=#51afef"
set -g window-status-separator ">>> "
set -g status-left '  '
set -g status-right '#{?client_prefix,#[fg=#ff665c],}#{session_name}  #[default] | 󰃰 %R%p %d-%b %A   '

#remap window index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g mode-keys vi

#remap
unbind C-b
unbind s # unbind select new session for attach client
# unbind i
unbind n # unbind change next window
unbind p # unbind change prev window
unbind c # unbind create new window
unbind f # unbind find text in open window
set-option -g prefix C-e # try lu
bind-key C-e send-prefix
bind C-l send-keys 'C-l' # default clear shell

# remap binds
bind o choose-session # NOTE: feels like no need for session manager i guess?
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9
bind t new-window
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'


#set inactive/active window styles
set -g escape-time 0

#open panes in same dir
bind -n M-+ split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"
bind -n M-Left resize-pane -L 5
bind -n M-Right resize-pane -R 5
bind -n M-Up resize-pane -U 2
bind -n M-Down resize-pane -D 2
# personal plugins/binds
bind r source-file ~/dotfiles/tmux/.config/tmux/tmux.conf

# scripts
bind h run-shell "tmux popup -E -w 60% -h 70% '~/.local/scripts/fzf-man.sh'" # need a better man launcher/searcher
# sessions related
bind s run-shell "tmux popup -E -w 60% -h 70% ~/.local/scripts/tmux_session.sh" #
bind S run-shell "~/.local/scripts/tmux_session.sh ~/.local/scripts/"
bind n run-shell "~/.local/scripts/tmux_session.sh ~/.config/nvim/" # not neccessarily for nvim config session
bind v run-shell "~/.local/scripts/tmux_session.sh ~/Documents/Vaults/"
bind g run-shell "~/.local/scripts/tmux_session.sh ~/projects/gigachad/gigachad-node-ts/"
bind u run-shell "~/.local/scripts/tmux_session.sh ~/projects/gigachad/gigachad-ui-vite/"
bind c run-shell "~/.local/scripts/tmux_session.sh ~/work/contract-root/"
bind p run-shell "tmux popup -E -w 60% -h 70% '~/.local/scripts/tmux_session.sh ~/projects/'"
bind P run-shell "tmux popup -E -w 60% -h 70% '~/.local/scripts/tmux_session.sh ~/projects/learn/'"
# lazygit
bind l run-shell 'tmux neww sh -c "cd \$(tmux display-message -p \"#{pane_current_path}\") && lazygit"'

#Plugins tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'
