set -g @continuum-restore 'on'
# set -ga terminal-overrides ",xterm*:Tc"
set-option -g terminal-overrides ",xterm-256color:RGB"
set-option -g default-terminal 'screen-256color'
set -g status-right-length 200
set -g mouse on

#remap
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

bind r source-file ~/dotfiles/tmux/.config/tmux/tmux.conf

#remap window index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#set vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#maybe i use 1 as prev and 2 as next ; hurts my fingers using 1-9
bind -n M-1 prev
bind -n M-2 next
# bind -n M-1 select-window -t :1
# bind -n C-2 select-window -t :2
# bind -n C-3 select-window -t :3
# bind -n C-4 select-window -t :4
# bind -n C-5 select-window -t :5
# bind -n C-6 select-window -t :6
# bind -n C-7 select-window -t :7
# bind -n C-8 select-window -t :8
# bind -n C-9 select-window -t :9

#set inactive/active window styles
set -g pane-active-border-style "fg=colour244"
set -g pane-border-style "fg=magenta"
set -g escape-time 0
#Custom KeyBinds
# bind -n M-H previous-window
# bind -n M-L next-window
bind -n C-t new-window

#open panes in same dir
bind -n M-+ split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"

#Plugins tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{b:pane_current_path}"

set -g @catppuccin_status_modules_right "application session cpu date_time"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_date_time_text "%H:%M %d-%m"


run '$XDG_CONFIG_HOME/tmux/plugins/tpm'
#run '~/.tmux/plugins/tpm/tpm' -> if is not in home
