-- vim.api.nvim_set_hl(0, "LineNr", { fg = "white" })
-- vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "brown" })
vim.cmd("highlight @markup.heading.1.markdown guifg=#82aaff")
vim.cmd("highlight @markup.heading.2.markdown guifg=#ffc777")
vim.cmd("highlight @markup.heading.3.markdown guifg=#c3e88d")
vim.cmd("highlight @markup.heading.4.markdown guifg=#4fd6be")
vim.cmd("highlight @markup.heading.5.markdown guifg=#c099ff")
vim.cmd("highlight @markup.heading.6.markdown guifg=#fca7ea")
vim.cmd("highlight RenderMarkdownH1Bg guibg=#273849")
vim.cmd("highlight RenderMarkdownH2Bg guibg=#252a3f")
vim.cmd("highlight RenderMarkdownH3Bg guibg=#3a273a")
vim.cmd("highlight RenderMarkdownH4Bg guibg=#394b70")
vim.cmd("highlight RenderMarkdownH5Bg guibg=#394b70")
vim.cmd("highlight RenderMarkdownH6Bg guibg=#394b70")

vim.api.nvim_set_hl(0, "lualine_a_normal", { fg = "#1d202f", bg = "#7aa2f7", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_insert", { fg = "#1d202f", bg = "#9ece6a", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_visual", { fg = "#1d202f", bg = "#bb9af7", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_replace", { fg = "#1d202f", bg = "#f7768e", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_command", { fg = "#1d202f", bg = "#e0af68", bold = true })
