version = 3
enable_cursor_positioning = true
final_space = true

[secondary_prompt]
  template = '▶ '
  foreground = 'green'

[transient_prompt]
  template = '➜ '
  foreground = 'green'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{ if eq .Code 0 }}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  overflow = 'break'
  newline = true

  [[blocks.segments]]
    template = '{{ if .Segments.Git.RepoName}}󰜥 {{ if eq .Segments.Git.Dir .PWD }} {{.Segments.Git.RepoName}}{{else}} {{.Path}} {{end}} {{else}} {{if not .Writable}}🔒 {{end}}{{.Path}} {{end}}'
    foreground = '#51afef'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      max_depth = 2
      style = 'agnoster_short'

      [blocks.segments.properties.mapped_locations]
        '~/.local/share/applications' = '󰀻 Applications'
        '~/Downloads' = '  Downloads'
        '~/Downloads/*' = '  Downloads'

  [[blocks.segments]]
    template = '{{.HEAD}} {{ if and (gt .Ahead 0) (eq .Behind 0) }} <orange>⇡{{.Ahead}}</>{{ end }}{{ if and (eq .Ahead 0) (gt .Behind 0) }} <red>⇣{{.Behind}}</>{{ end }}{{ if and (gt .Ahead 0) (gt .Behind 0) }} <green> </><#f5a97f>⇡{{.Ahead}}</><red>⇣{{.Behind}}</>{{ end }}{{ if .Staging.Changed }}{{if gt .Staging.Added 0 }} <yellow>+{{.Staging.Added}}</>{{else if gt .Staging.Modified 0}} <yellow>+{{.Staging.Modified}}</>{{else}} <yellow>{{.Staging.String}}</>{{ end }}{{ end }}{{ if .Working.Changed }} <green>{{.Working.String}}</>{{ end }}{{ if gt .StashCount 0 }} <cyan>${{ .StashCount}}</>{{ end }}'
    foreground = '#a9a1e1'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = '<green></> '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = false
      full_branch_path = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      source = 'cli'
      tag_icon = ' '

      [blocks.segments.properties.mapped_branches]
        'bugfix/*' = 'bug::'
        'build/*' = 'build::'
        'feature/*' = 'feat::'
        'hotfix/*' = 'hf::'
        'merge/*' = 'merge::'
        'release/*' = 'rel::'
        'test/*' = 'test::'

      [blocks.segments.properties.staging]
        [blocks.segments.properties.staging.modified]
          foreground = 'green'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if .Code }}✗{{ else }}➜{{end}}'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{ if eq .Code 0}}green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = '{{ .FormattedMs}} '
    foreground = 'cyan'
    type = 'executiontime'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'round'
      threshold = 5000

  [[blocks.segments]]
    template = '   {{ .Full }} '
    foreground = '#1e9758'
    type = 'cmake'

    [blocks.segments.properties]
      cache_duration = 'none'
      extensions = ['*.cmake', 'CMakeLists.txt', 'Makefile']

  [[blocks.segments]]
    template = ' ☸ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} '
    foreground = '#ebcc35'
    type = 'kubectl'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Context }} '
    foreground = '#0B59E7'
    type = 'docker'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '   {{ .Full }} '
    foreground = '#7fd5ea'
    type = 'go'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#906cff'
    type = 'python'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' C# {{ .Full }} '
    foreground = '#00ffff'
    type = 'dotnet'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#422251'
    type = 'elixir'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }}'
    foreground = '#4063D8'
    type = 'java'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }}'
    foreground = '#100e23'
    type = 'haskell'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' 🦀 {{ .Full }} '
    foreground = '#99908a'
    type = 'rust'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#6ca35e'
    type = 'node'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }}'
    foreground = '#06a4ce'
    type = 'dart'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = 'blue'
    type = 'lua'

    [blocks.segments.properties]
      cache_duration = 'none'
