preload =~/Media/Pictures/Wallpaper/Yae-Ei.jpg
preload =~/Media/Pictures/Wallpaper/Fantasy-Landscape.png
preload =~/Media/Pictures/Wallpaper/anime-girl-abyss.png
preload =~/Media/Pictures/Wallpaper/serene.jpg

wallpaper=DP-1,~/Media/Pictures/Wallpaper/serene.jpg
wallpaper=DP-2, ~/Media/Pictures/Wallpaper/Fantasy-Landscape.png
