# main keybind
bind = $super, RETURN, exec, $terminal
bind = $super, q, killactive,
bind = $super, End, exit,
bind = $super, t, togglefloating,
bind = $super, e, exec, $fileManager
bind = $super, d, exec, $browser
bind = $super, b, exec, brave
bind = $super, r, exec, $menu
bind = $super, F7, exec, $waybar # reload waybar
bind = $super, F8, exec, $cliphist
bind = $super, F9, exec, $gamemode
bind = $super, F10, exec, alacritty --title HTOP -e htop
bind = , F10, exec, alacritty --title BTOP -e btop
bind = , F11, fullscreen,
bind = ,Print, exec, $screenshot # bind with super cuz htop
# bind = $super, m, exit,
# bind = $super, p, pseudo, # dwindle
# bind = $super, o, togglesplit, # dwindle

# special workspaces
bind = Alt, Tab, togglespecialworkspace, Firefox
bind = $super, m, togglespecialworkspace, Random
bind = $super, o, togglespecialworkspace, Libre-Office
bind = $super, n, togglespecialworkspace, Obsidian
bind = $super, F10, togglespecialworkspace, TOP

# Switch workspaces with mainMod + [0-9]
bind = $super, 1, workspace, 1
bind = $super, 2, workspace, 2
bind = $super, 3, workspace, 3
bind = $super, 4, workspace, 4
bind = $super, 5, workspace, 5
bind = $super, 6, workspace, 6
bind = $super, 7, workspace, 7
bind = $super, 8, workspace, 8
bind = $super, 9, workspace, 9
bind = $super, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $super SHIFT, 1, movetoworkspace, 1
bind = $super SHIFT, 2, movetoworkspace, 2
bind = $super SHIFT, 3, movetoworkspace, 3
bind = $super SHIFT, 4, movetoworkspace, 4
bind = $super SHIFT, 5, movetoworkspace, 5
bind = $super SHIFT, 6, movetoworkspace, 6
bind = $super SHIFT, 7, movetoworkspace, 7
bind = $super SHIFT, 8, movetoworkspace, 8
bind = $super SHIFT, 9, movetoworkspace, 9
bind = $super SHIFT, 0, movetoworkspace, 10

# vm
bind = $super,v,submap,passthru
submap= passthru
bind = $super, Escape, submap,reset
submap=reset
# change wallpaper
bind = $super, F1, exec, $w11
bind = $super SHIFT, F1, exec, $w12
bind = $super, F2, exec, $w21
bind = $super SHIFT, F2, exec, $w22
bind = $super, F3, exec, $w31
bind = $super SHIFT, F3, exec, $w32
bind = $super, F4, exec, $w41
bind = $super SHIFT, F4, exec, $w42
bind = $super, F5, exec, $w51
bind = $super SHIFT, F5, exec, $w52
bind = $super, F6, exec, $w61
bind = $super SHIFT, F6, exec, $w62

# change focus
bind = $super, h, movefocus, l
bind = $super, l, movefocus, r
bind = $super, k, movefocus, u
bind = $super, j, movefocus, d

# Scroll through existing workspaces with mainMod + scroll
bind = $super,tab, workspace,previous
bind = $super, mouse_down, workspace, e+1
bind = $super, mouse_up, workspace, e-1
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $super, mouse:272, movewindow
bindm = $super, mouse:273, resizewindow
