$super = SUPER
$scripts = $HOME/.config/hypr/scripts
# $terminal = kitty -o allow_remote_control=socket-only --listen-on unix:/tmp/kitty
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun -theme "~/.config/rofi/launchers/applaunch/applaunch.rasi"
$cliphist = $scripts/clipboard.sh
$browser = brave
$gamemode = $scripts/gamemode.sh

# Source
source = ~/.config/hypr/settings/env.conf # load this first
source = ~/.config/hypr/settings/exec.conf
source = ~/.config/hypr/settings/config.conf
source = ~/.config/hypr/settings/animation.conf
source = ~/.config/hypr/settings/style.conf
source = ~/.config/hypr/keymap.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
