# main keybind
bind = $super, RETURN, exec, $terminal
bind = $super, q, killactive,
bind = $super, m, exit,
bind = $super, t, togglefloating,
bind = $super, f, fullscreen,
bind = $super, p, pseudo, # dwindle
bind = $super, o, togglesplit, # dwindle
bind = $super, w, exec, $wbreload #test reload waybar
bind = $super, e, exec, $fileManager
bind = $super, b, exec, $browser
bind = $super, r, exec, $menu
bind = $super, c, exec, $cliphist
bind = $super, g, exec, $screenshot
bind = $super, F9, exec,$gamemode

# change focus
bind = $super, h, movefocus, l
bind = $super, l, movefocus, r
bind = $super, k, movefocus, u
bind = $super, j, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $super, 1, workspace, 1
bind = $super, 2, workspace, 2
bind = $super, 3, workspace, 3
bind = $super, 4, workspace, 4
bind = $super, 5, workspace, 5
bind = $super, 6, workspace, 6
bind = $super, 7, workspace, 7
bind = $super, 8, workspace, 8
bind = $super, 9, workspace, 9
bind = $super, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $super SHIFT, 1, movetoworkspace, 1
bind = $super SHIFT, 2, movetoworkspace, 2
bind = $super SHIFT, 3, movetoworkspace, 3
bind = $super SHIFT, 4, movetoworkspace, 4
bind = $super SHIFT, 5, movetoworkspace, 5
bind = $super SHIFT, 6, movetoworkspace, 6
bind = $super SHIFT, 7, movetoworkspace, 7
bind = $super SHIFT, 8, movetoworkspace, 8
bind = $super SHIFT, 9, movetoworkspace, 9
bind = $super SHIFT, 0, movetoworkspace, 10

# change wallpaper
bind = $super, F1, exec, $w11
bind = $super SHIFT, F1, exec, $w12
bind = $super, F2, exec, $w21
bind = $super SHIFT, F2, exec, $w22
bind = $super, F3, exec, $w31
bind = $super SHIFT, F3, exec, $w32
bind = $super, F4, exec, $w41
bind = $super SHIFT, F4, exec, $w42
bind = $super, F5, exec, $w51
bind = $super SHIFT, F5, exec, $w52
bind = $super, F6, exec, $w61
bind = $super SHIFT, F6, exec, $w62

# special workspaces
bind = $super, S, togglespecialworkspace, browser
bind = $super, n, togglespecialworkspace, notes

# Scroll through existing workspaces with mainMod + scroll
bind = $super, mouse_down, workspace, e+1
bind = $super, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $super, mouse:272, movewindow
bindm = $super, mouse:273, resizewindow
