# monitor
monitor=DP-1,1920x1080@240,0x0,1
monitor=DP-2,1920x1080@144,1920x0,1

# Execute your favorite apps at launch
exec-once = hyprpaper & waybar & dunst
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --type text --watch cliphist store

# Source
source = ~/.config/hypr/env.conf # load this first
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keymaps.conf


