# preload wallpaper
preload =~/Media/Pictures/wallpaper/Yae-Ei.jpg
preload =~/Media/Pictures/wallpaper/animebeach.jpg
preload =~/Media/Pictures/wallpaper/starrynight.jpg
preload =~/Media/Pictures/wallpaper/animegirlstairs.jpg
preload =~/Media/Pictures/wallpaper/countrygirl.jpg
preload =~/Media/Pictures/wallpaper/frieren-fern.jpg

# default
wallpaper=DP-1, ~/Media/Pictures/wallpaper/animebeach.jpg
wallpaper=DP-2, ~/Media/Pictures/wallpaper/starrynight.jpg

splash=false
