# copy from jakoolit
[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
lazy = true
command = "kitty --class float_term"
class = "float_term"
size = "75% 60%"
