# copy from jakoolit
[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.ani-cli]
animation = "fromTop"
lazy = true
command = "kitty --class float_term --title ani-cli -e ani-cli"
class = "float_term"
size = "75% 60%"
