windowrulev2 = suppressevent maximize, class:.*

#for xwaylandvideobridge
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$
#for xwaylandvideobridge

# default applications on launch
windowrulev2 = workspace 1, class:^(kitty)$
windowrulev2 = workspace 2, class:^(Alacritty)$
windowrulev2 = animation popin, class:^(kitty)$
windowrulev2 = workspace 5, class:^(vesktop)$
windowrulev2 = workspace 4 silent, class:^(steam)$
windowrulev2 = workspace special:notes, class:^(obsidian)$
windowrulev2 = workspace special:browser, class:^(firefox)$

# window behaviour
windowrulev2 = float, class:^(steam)$, title:^(Friends List)$
windowrulev2 = float, class:^(Display)$, title:^(Pan Icon)$
windowrulev2 = float, class:^(Display)$, title:^(Commands)$

# steam_app_\d

# image
windowrulev2 = workspace 8, class:^(Display)$, title:(ImageMagick)
windowrulev2 = workspace 8, class:^(Display)$, title:^(Pan Icon)$
windowrulev2 = workspace 8, class:^(Display)$, title:^(Commands)$
# win 9 for settings, this is ugly, find a workaround
windowrulev2 = workspace 9, class:^(nemo)$
windowrulev2 = workspace 9, class:^(blueman-manager)$
windowrulev2 = workspace 9, class:^(pavucontrol)$
windowrulev2 = workspace 9, class:^(nm-connection-editor)$


# workspace
workspace=special:browser,border:false,rouding:false,gapsin:0,gapsout:0
workspace=special:notes,border:false,rouding:false,gapsin:0,gapsout:0
workspace=1,name:shell,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:false
workspace=2,name:any,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:true
workspace=3,name:Games,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:true
workspace=4,name:steam,monitor:DP-2,gapsin:10,gapsout:20,border:false,rouding:true
workspace=5,name:vesktop,monitor:DP-2,gapsin:10,gapsout:20,border:false,rouding:true
workspace=6,name:Games,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=7,name:Games,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=8,name:Games,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=0,name:Games,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true

