windowrulev2 = suppressevent maximize, class:.*

#for xwaylandvideobridge
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$
#for xwaylandvideobridge

#android studio
windowrulev2 = float, workspace 1, class:^(Emulator)$
windowrulev2 = workspace 2,class:^(jetbrains-studio)$
# default applications on launch
windowrulev2 = workspace 1, class:^(kitty)$
windowrulev2 = workspace 2, class:^(mpv)$
windowrulev2 = animation popin, class:^(kitty)$
windowrulev2 = workspace special:HTOP, class:^(Alacritty)$, title:^(Alacritty)$
windowrulev2 = workspace special:Obsidian, class:^(obsidian)$
windowrulev2 = workspace special:Libre-Office, class:^(libreoffice)
windowrulev2 = workspace special:Firefox, class:^(firefox)$

#discord
windowrulev2 = workspace 7, class:^(vesktop)$
# steam_app_\d
windowrulev2 = workspace 8 silent, class:^(steam)$, title:^(Steam)$
windowrulev2 = workspace 8, class:^(steam)$, title:^(Special Offers)$
windowrulev2 = workspace 8, class:^(steam)$, title:^(Friends List)$
windowrulev2 = workspace 8, class:^(steam)$, title:^(Steam Settings)$
windowrulev2 = float, class:^(steam)$, title:^(Friends List)$
windowrulev2 = float, class:^(Display)$, title:^(Pan Icon)$
windowrulev2 = float, class:^(Display)$, title:^(Commands)$

# 9 for image/Picture-in-Picture
windowrulev2 = workspace 9, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = workspace 9, class:^(Display)$, title:^(ImageMagick)
windowrulev2 = workspace 9, class:^(Display)$, title:^(Pan Icon)
windowrulev2 = workspace 9, class:^(Display)$, title:^(Commands)
windowrulev2 = workspace 9, class:^(nemo)$
# windowrulev2 = workspace 9, class:^(Nsxiv)$, title:^(nsxiv)$

# win 10 for settings, this is ugly, find a workaround
windowrulev2 = workspace 10, class:^(qt5ct)$
windowrulev2 = workspace 10, class:^(qt6ct)$
windowrulev2 = workspace 10, class:^(nwg-look)$
windowrulev2 = workspace 10, class:^(blueman-manager)$
windowrulev2 = workspace 10, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = workspace 10, class:^(nm-connection-editor)$


# workspace
# special
workspace=special:Firefox,border:false,rouding:false,gapsin:0,gapsout:0
workspace=special:Obsidian,border:false,rouding:false,gapsin:0,gapsout:0
workspace=special:Libre-Office,border:false,rouding:false,gapsin:0,gapsout:0
workspace=special:HTOP,border:false,rouding:false,gapsin:0,gapsout:0

# normal
workspace=1,name:shell,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:false
workspace=2,name:any,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:true
workspace=3,name:Games,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:true
workspace=4,name:rand,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=5,name:ran,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=6,name:ran,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=7,name:vesktop,monitor:DP-2,gapsin:10,gapsout:20,border:false,rouding:true
workspace=8,name:steam,monitor:DP-2,gapsin:10,gapsout:20,border:false,rouding:true
workspace=9,name:media,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=10,name:settings,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true

