# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrule= float,nemo
# windowrule= float,blueman-manager
# windowrule= float,pavucontrol

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

#for xwaylandvideobridge
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$

# default applications on launch
windowrulev2 = workspace 1, class:^(kitty)$
windowrulev2 = animation popin, class:^(kitty)$
windowrulev2 = workspace 5, class:^(vesktop)$
windowrulev2 = workspace 4 silent, class:^(steam)$
windowrulev2 = workspace special:notes, class:^(obsidian)$
windowrulev2 = workspace special:browser, class:^(firefox)$
windowrulev2 = float, class:^(steam)$, title:^(Friends List)$

# steam_app_\d

# win 9 for settings, this is ugly, find a workaround
windowrulev2 = workspace 9, class:^(nemo)$
windowrulev2 = workspace 9, class:^(blueman-manager)$
windowrulev2 = workspace 9, class:^(pavucontrol)$


# workspace
workspace=special:browser,border:false,rouding:false,gapsin:0,gapsout:0
workspace=special:notes,border:false,rouding:false,gapsin:0,gapsout:0
workspace=1,name:Term,monitor:DP-1,gapsin:5,gapsout:2,border:false,rouding:true
workspace=2,name:Browser,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:true
workspace=3,name:Vesktop,monitor:DP-1,gapsin:0,gapsout:0,border:false,rouding:true
workspace=4,name:stuff,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=5,name:stuff,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=6,name:stuff,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=7,name:stuff,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=8,name:stuff,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=9,name:stuff,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true
workspace=0,name:stuff,monitor:DP-2,gapsin:0,gapsout:0,border:false,rouding:true

