# full,resized,wal,thumb,fastresize,kmeans
backend = "kmeans"
color_space = "labmixed"
palette = "dark16"
#  1          Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite
threshold = 11
# generate colorscheme and populate to respective dir
[templates]
cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'
hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/wallust/wallust-hyprland.conf'
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors/wallust-colors-rofi.rasi'
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/wallust/colors-waybar.css'
