return {
  "m4xshen/hardtime.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  opts = {
    disabled_filetypes = {
      "git",
      "dbui",
      "checkhealth",
      "Diffview*",
      "httpResult",
      "prompt",
      "dapui",
      "query",
      "fugitive",
      "help",
      "qf",
      "NvimTree",
      "lazy",
      "undotree",
      "markdown",
      "mason",
      "oil",
      "minifiles",
      "fzf",
      "TelescopePrompt",
      "aerial",
      "alpha",
      "Dressing*",
      "lspinfo",
      "Neogit*",
      "neotest%-summary",
      "neo%-tree*",
      "netrw",
      "noice",
      "notify",
      "Trouble",
      "trouble",
    },
    max_count = 4,
  },
}
