return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"c",
				"c_sharp",
				"cmake",
				"css",
				"dart",
				"dockerfile",
				"gitignore",
				"go",
				"http",
				"json5",
				"json",
				"luadoc",
				"make",
				"regex",
				"sql",
				"svelte",
				"xml",
				"yaml",
				"toml",
				"lua",
				"vim",
				"vimdoc",
				"markdown_inline",
				"markdown",
				"html",
				"rust",
				"typescript",
			},
			highlight = { enable = true },
			indent = { enable = true },
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					-- scope_incremental = "<C-s>",
					node_decremental = "<C-backspace>",
				},
			},
		})
	end,
}
