# vim:fileencoding=utf-8:foldmethod=marker

font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono NF Bold
bold_italic_font JetBrainsMono NF Bold Italic
italic_font      JetBrainsMono NF Italic
font_size 11.0

cursor_shape block
scrollback_lines 10000
window_padding_width 0 5 0 5

# foreground #dddddd
# background #000000
background_opacity 0.80
background_blur 100

editor .
map ctrl+shift+t no_op
map ctrl+shift+q discard_event
map ctrl+shift+w discard_event

enable_audio_bell no

confirm_os_window_close 0
