# vim:fileencoding=utf-8:foldmethod=marker

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
cursor_shape block
scrollback_lines 10000
window_padding_width 5 10 0 10
foreground
background
background_opacity 0.80
background_blur 100
editor .
map ctrl+shift+t no_op

