# vim:fileencoding=utf-8:foldmethod=marker
font_size 11.0

cursor_shape block
scrollback_lines 10000
window_padding_width 0 0 0 3

# foreground #dddddd
# background #000000
background_opacity 0.85
background_blur 700

editor .
map ctrl+shift+t no_op
map ctrl+shift+q discard_event
map ctrl+shift+w discard_event

enable_audio_bell no

confirm_os_window_close 0

# BEGIN_KITTY_THEME
# Doom Vibrant
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      family="JetBrainsMono Nerd Font"
bold_italic_font family="JetBrainsMono Nerd Font"
# END_KITTY_FONTS
