font=JetBrainsMono Nerd Font:size=12
font-bold=JetBrainsMono Nerd Font:style=Bold:size=12
font-italic=JetBrainsMono Nerd Font:style=Italic:size=12
font-bold-italic=JetBrainsMono Nerd Font:style=Bold Italic:size=12

pad=5x2 center-when-maximized-and-fullscreen

[scrollback]
lines=10000

[colors-dark]
alpha=0.90
foreground=dcdfe4
#background=282c34
background=090a0a
selection-foreground=000000
selection-background=fffacd
urls=0087bd

## Normal colors
regular0=282c34
regular1=e06c75
regular2=98c379
regular3=e5c07b
regular4=61afef
regular5=c678dd
regular6=56b6c2
regular7=dcdfe4

## Bright colors
bright0=5d677a    # bright black
bright1=e06c75    # bright red
bright2=98c379    # bright green
bright3=e5c07b    # bright yellow
bright4=61afef    # bright blue
bright5=c678dd    # bright magenta
bright6=56b6c2    # bright cyan
bright7=dcdfe4    # bright white

