local harpoon = require("harpoon")

harpoon:setup()

vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
end, { desc = "Harpoon add list" })
vim.keymap.set("n", "<space><space>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Add harpoon list" })
vim.keymap.set("n", "<leader>1", function()
	harpoon:list():select(1)
end, { desc = "Harpoon list 1" })
vim.keymap.set("n", "<leader>2", function()
	harpoon:list():select(2)
end, { desc = "Harpoon list 2" })
vim.keymap.set("n", "<leader>3", function()
	harpoon:list():select(3)
end, { desc = "Harpoon list 3" })
vim.keymap.set("n", "<leader>4", function()
	harpoon:list():select(4)
end, { desc = "Harpoon list 4" })
vim.keymap.set("n", "<leader>5", function()
	harpoon:list():select(5)
end, { desc = "Harpoon list 5" })
